apiVersion: v1
kind: Service
metadata:
  name: miw-customer-webapp
  labels:
    run: miw-customer-webapp
spec:
  type: NodePort
  clusterIP: None
  ports:
  - port: 80
    nodePort: 4200
    protocol: TCP
  selector:
    run: customer-webapp

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-webapp
spec:
  selector:
    matchLabels:
      run: customer-webapp
  replicas: 1
  template:
    metadata:
      labels:
        run: customer-webapp
    spec:
      containers:
      - name: customer-webapp
        image: lars14/music-instruments-webshop-test:release0.0.1
        ports:
        - containerPort: 80
