apiVersion: v1
kind: Service
metadata:
  name: miw-product-service
  labels:
    run: miw-product-service
spec:
  type: NodePort
  clusterIP: None
  ports:
  - port: 80
    nodePort: 5010
    protocol: TCP
  selector:
    run: product-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      run: product-service
  replicas: 1
  template:
    metadata:
      labels:
        run: product-service
    spec:
      containers:
      - name: product-service
        image: lars14/miw-productservice:release0.0.2
        ports:
        - containerPort: 80
